name = "Beacon"
prefix = "beacon"
author = "CreepPork"
files = [
    "mod.cpp",
    "logo.paa",
    "*.dll",
    "*.so",
    "LICENSE",
    "README.md",
    "meta.cpp"
]

include = ["./include"]

key_name = "{{prefix}}_{{version}}"

releasebuild = [
    "@zip @beacon",
    "!release_build"
]

[scripts.release_build]
steps = [
    "python3 tools/release_build.py"
]

[header_exts]
version = "{{git \"id 8\"}}"
