name = "Beacon"
prefix = "beacon"
author = "CreepPork"
files = [
    "mod.cpp",
    "logo.paa",
    "*.dll",
    "*.so",
    "LICENSE",
    "README.md",
    "meta.cpp"
]

key_name = "{{prefix}}_{{version}}"

releasebuild = [
    "@zip @beacon_{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"
