name = "Beacon"
prefix = "beacon"
author = "CreepPork"
files = [
    "mod.cpp",
    "logo.paa",
    "*.dll",
    "*.so",
    "LICENSE",
    "README.md",
    "meta.cpp"
]

include = ["./include"]

key_name = "{{prefix}}_{{version}}"

postbuild = [
    "!build"
]

[scripts.build]
steps = [
    "bash ./build.sh"
]

releasebuild = [
    "@zip @beacon",
]

[header_exts]
version = "{{git \"id 8\"}}"
