#define MAINPREFIX x
#define PREFIX beacon

#include "script_version.hpp"

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 1.96

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(beacon - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(beacon - COMPONENT)
#endif